### PR TITLE
Switch logger to github.com/google/logger

### PR DESCRIPTION
**Pull request by discentem**
This PR
- switches the logger to google/logger to easily enable writing logs to stdout during interactive runs
- adds a new flag `-verbose` which can be passed during interactive runs to get the logs in stdout. This flag defaults to false.
- adds a second new flag `-eventlog` which can be set to false if, for some reason, there is a desire to do a cabbie run without logging to event log. This defaults to true obviously, so by default cabbie continues to log to event log. 

**NOTES/CONSIDERATIONS:** 

- ~I know I've broken some of the some of the tests :( Unfortunately I can't figure out how to do dependency injection for google/logger. Any guidance the Cabbie authors can provide on fixing the tests would be much appreciated :)~ 
- The change to google/logger appears to remove the ability to customize the event id when logging to event log. I could not find an obvious way to pass an event id to google/logger.

### CODE REVIEW

**Comment by discentem** [comment]
I've fixed the tests now. But: they might be considered "bad" now because I'm not mocking the logger. I'm initializing it and sending the logs nowhere. As previously mentioned, please let me know if you have concerns/guidance on the tests.

**Comment by ItsMattL** [comment]
Thanks for the CL. The main issue with adopting logger is that it doesn't support unique event IDs when logging to event log. This is going to conflict with other recent changes being put into cabbie to differentiate log events.

**Comment by discentem** [comment]
Makes sense. I saw that you filed https://github.com/google/logger/issues/42 just now, thanks for doing that!

**Comment by discentem** [comment]
@ItsMattL @cjgenevi Would you folks accept a PR that (for now) abstracts the logger and lets me swap out the elog to google/logger behind a flag? This way by default you could retain eventIDs and I could get the things I want out of google/logger?

**Pull request closed without merging**
