### PR TITLE
abstraction around debug.Log interface so that log messages can optionally be sent to stdout

### PR DESCRIPTION
**Pull request by discentem**
Changes:
- If cabbie is run with `--showOutput`, log messages are written to stdout in addition to eventlog. By default, as before, nothing is sent to stdout. Event IDs are still retained in the event log, [which was a concern last time I submitted a similar change](https://github.com/google/cabbie/pull/56#issuecomment-848949033)

- Currently if [`config.regLoad(cablib.RegPath)`](https://github.com/google/cabbie/pull/94/files#diff-5d8a7fbb321191a8b19e21977488f65586a946d25a97405824b522927db1d040R535) fails, this logs an error. This PR changes that to warning as fallback defaults are set

### CODE REVIEW

**Comment by ItsMattL** [comment]
Have a look at the new v1.0.5 release. We just changed logging packages and are no longer dependent on/limited by the original eventlog package.

**Comment by discentem** [comment]
Is this consider solved with any further code changes? On the surface it seems like yes 👍 because deck can simultaneously log to eventlog and stdout out-of-the-box?

**Comment by discentem** [comment]
> Have a look at the new v1.0.5 release. We just changed logging packages and are no longer dependent on/limited by the original eventlog package.

Or are you suggesting that I can add a similar feature/flag now and it's just much simpler because of deck?

**Comment by ItsMattL** [comment]
I think deck obsoletes the PR since it does support piping all log events to different places, including stdout for debug. But please feel free to test and see if any adjustments are required.

**Comment by discentem** [comment]
Ah yep, looks like Deck resolves this. `--debug` causes everything to print to stdout

**Pull request closed without merging**
