### PR TITLE
Automated Github releases with Github Actions! 

### PR DESCRIPTION
**Pull request by discentem**
Apologies for the multiple false starts! I was doing a bunch of testing on my fork and a few times I accidentally PRed against google/cabbie instead of discentem/cabbie. 

So what does this PR actually do? 

- Adds a Github Action to make sure every PR builds in `build_pr.yml`
- Adds a second Github Action to automatically build and release `cabbie.exe` on every push to `master` in `build_release.yml`. _Note_: every change is considered a minor release based on the `minor_pattern` regex I wrote. I figured this was the best way to automatically version. See https://github.com/discentem/cabbie/blob/master/.github/workflows/build_release.yml#L32 and https://github.com/PaulHatch/semantic-version#usage for more context. There are many ways the automatic versioning could work and I'm happy to make changes as desired. 
- Adds a third Github Action to build and release `cabbie.exe` if any tag is manually created. I figured this is useful if you want to manually release with a manually created version number. 

Please let know if you have feedback or questions! Thanks!

### CODE REVIEW

**Comment by discentem** [comment]
I've just realized something, which may be tricky to figure out: we probably should _not_ build a release if _only_ `readme.md` changes. And there may be other files we want to ignore as well. See https://github.com/PaulHatch/semantic-version/issues/31 for discussion about excluding files. 

Please let me know if I should exclude the readme or any other files.

**Comment by TsekNet** [comment]
Just wondering - has https://goreleaser.com been considered? Seems like goreleaser would accomplish what you're trying to do in this PR, in a potentially simpler fashion.

**Comment by discentem** [comment]
TIL about https://goreleaser.com. I looked over the goreleaser docs quickly but I'm not sure if I'll be able to work on a goreleaser version of this any time soon. If you'd prefer to the goreleaser direction, feel free to close this though.

**Comment by TsekNet** [comment]
FYI @discentem - Cabbie can now be downloaded via [releases](https://github.com/google/cabbie/releases)

**Pull request closed without merging**
